name: Fetch Page

on:
  schedule:
    # 每 10 分钟运行一次
    - cron: '*/10 * * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 给予写入仓库内容的权限

    steps:
      - name: 检查代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # 指定您需要的 Python 版本

      - name: 安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 检查文件更新时间
        id: check_file
        run: |
          # 获取文件最后一次提交时间（秒）
          last_commit_ts=$(git log -1 --format=%ct -- proxy_ip.yml)
          now_ts=$(date +%s)
          diff=$((now_ts - last_commit_ts))
          if [ $diff -le 1800 ]; then
            echo "changed_within_1h=true" >> $GITHUB_OUTPUT
          else
            echo "changed_within_1h=false" >> $GITHUB_OUTPUT
          fi

      - name: 运行 Fetch_Page 脚本
        id: fetch_page
        run: python fetch_page.py

      - name: 运行 Fetch_IP 脚本
        id: fetch_ip
        if: steps.check_file.outputs.changed_within_1h == 'false'
        run: python fetch_ihuan_ip.py

      - name: 提交并推送更改
        run: |
          git config user.name 'mai19950'
          git config user.email 'underdog-95@outlook.com'

          PAGES_MSG="${{ steps.fetch_page.outputs.pages_msg || '' }}"
          PROXY_MSG="${{ steps.fetch_ip.outputs.proxy_msg || '' }}"

          if [ -n "$PAGES_MSG" ]; then
            COMMIT_MSG="$PAGES_MSG"
          elif [ -n "$PROXY_MSG" ]; then
            COMMIT_MSG="$PROXY_MSG"
          else
            echo "未检测到有效的提交消息，跳过提交。"
            exit 0
          fi

          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "$COMMIT_MSG"
            git push
          else
            echo "工作区没有变更，跳过提交。"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}